services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: treasuretoynepal
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./treasuretoy-be
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD}@db:5432/treasuretoynepal"
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: HS256
    volumes:
      - ./treasuretoy-be:/app
  frontend:
    build: ./treasuretoy-fe
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./treasuretoy-fe:/app
      - /app/node_modules


volumes:
  postgres_data: